# Generated by Django 4.2.3 on 2023-07-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_groups_account_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="date_joined",
        ),
        migrations.AlterField(
            model_name="account",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
