# Generated by Django 4.2.3 on 2023-07-25 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_account_date_joined_alter_account_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
