# Generated by Django 4.2.3 on 2023-09-07 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="created_at",
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(default="example@gmail.com", max_length=150),
        ),
        migrations.AddField(
            model_name="profile",
            name="fname",
            field=models.CharField(default="fname", max_length=150),
        ),
        migrations.AddField(
            model_name="profile",
            name="lname",
            field=models.CharField(default="lname", max_length=150),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.BigIntegerField(default="99999999"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterModelTable(
            name="profile",
            table="Address",
        ),
    ]
