# Generated by Django 4.2.3 on 2023-09-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_profile_created_at_profile_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="pincode",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
