# Generated by Django 4.2.3 on 2023-09-05 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0016_alter_productitem_product_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=150)),
                ("lname", models.CharField(max_length=150)),
                ("phone", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=150)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=150)),
                ("state", models.CharField(max_length=150)),
                ("pincode", models.PositiveIntegerField()),
                ("country", models.CharField(max_length=150)),
                ("total_price", models.IntegerField()),
                ("payment_mode", models.CharField(max_length=150)),
                ("payment_id", models.CharField(max_length=250, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("out for shipping", "out for shipping"),
                            ("completed", "completed"),
                            ("pending", "pending"),
                        ],
                        default="Pending",
                        max_length=150,
                    ),
                ),
                ("message", models.TextField(null=True)),
                ("tracking_no", models.CharField(max_length=150, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productitem",
                    ),
                ),
            ],
        ),
    ]
