# Generated by Django 4.2.3 on 2023-09-07 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_profile_created_at_profile_email_and_more"),
        ("orders", "0005_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="city",
        ),
        migrations.RemoveField(
            model_name="order",
            name="country",
        ),
        migrations.RemoveField(
            model_name="order",
            name="email",
        ),
        migrations.RemoveField(
            model_name="order",
            name="fname",
        ),
        migrations.RemoveField(
            model_name="order",
            name="lname",
        ),
        migrations.RemoveField(
            model_name="order",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="order",
            name="pincode",
        ),
        migrations.RemoveField(
            model_name="order",
            name="state",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="total_amount",
            field=models.PositiveIntegerField(default=1111),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.profile"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "completed"),
                    ("out for shipping", "out for shipping"),
                    ("pending", "pending"),
                ],
                default="Pending",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.IntegerField(),
        ),
    ]
