# Generated by Django 4.2.3 on 2023-09-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_remove_order_city_remove_order_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "completed"),
                    ("pending", "pending"),
                    ("out for shipping", "out for shipping"),
                ],
                default="Pending",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tracking_no",
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
