# Generated by Django 4.2.3 on 2023-09-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_remove_orderitem_total_amount_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("out for shipping", "out for shipping"),
                    ("completed", "completed"),
                ],
                default="Pending",
                max_length=150,
            ),
        ),
    ]
