# Generated by Django 4.2.3 on 2023-09-22 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_coupon_code_active"),
        ("orders", "0012_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="applied_coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.coupon_code",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "completed"),
                    ("pending", "pending"),
                    ("out for shipping", "out for shipping"),
                ],
                default="Pending",
                max_length=150,
            ),
        ),
    ]
