# Generated by Django 4.2.3 on 2023-10-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="message",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("completed", "completed"),
                    ("out for shipping", "out for shipping"),
                ],
                default="Pending",
                max_length=150,
            ),
        ),
    ]
