# Generated by Django 4.2.3 on 2023-07-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productitem",
            name="gender_id",
        ),
        migrations.AddField(
            model_name="productitem",
            name="gender",
            field=models.CharField(
                choices=[("M", "Men"), ("F", "Women")],
                default=1,
                max_length=1,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("boots", "Boots"),
                    ("casuals", "Casuals"),
                    ("formal", "Formal"),
                    ("sports", "Sports"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="Gender",
        ),
    ]
