# Generated by Django 4.2.3 on 2023-07-31 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="ProductItemGallery",
        ),
    ]
