# Generated by Django 4.2.3 on 2023-07-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_rename_image_productitemgallery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productitem",
            name="slug",
            field=models.SlugField(max_length=300, unique=True),
        ),
    ]
