# Generated by Django 4.2.3 on 2023-07-31 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_productitem_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="productitem",
            name="createdDate",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="productitem",
            name="modifiedDate",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
