# Generated by Django 4.2.3 on 2023-08-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_productitemgallery_productitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productitem",
            name="gender",
            field=models.CharField(
                choices=[("M", "Men"), ("F", "Women")], max_length=1
            ),
        ),
    ]
