# Generated by Django 4.2.3 on 2023-08-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_productitem_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="productitem",
            name="img",
            field=models.ImageField(
                default="there is no image", upload_to="img/mainImg"
            ),
        ),
    ]
