# Generated by Django 4.2.3 on 2023-08-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_productitem_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productitem",
            name="img",
            field=models.ImageField(upload_to="img/mainImg"),
        ),
    ]
