# Generated by Django 4.2.3 on 2023-08-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_alter_productitem_img_alter_productitemgallery_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(default="No file choosen", upload_to="category"),
        ),
        migrations.AlterField(
            model_name="productitem",
            name="img",
            field=models.ImageField(upload_to="img"),
        ),
        migrations.AlterField(
            model_name="productitemgallery",
            name="image",
            field=models.ImageField(upload_to="image"),
        ),
    ]
