# Generated by Django 4.2.3 on 2023-08-02 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_productitem_createddate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productitemgallery",
            name="productItem",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_images",
                to="products.productitem",
            ),
        ),
    ]
