# Generated by Django 4.2.3 on 2023-09-05 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_alter_productitemgallery_productitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productitem",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_item",
                to="products.product",
            ),
        ),
    ]
