# Generated by Django 4.2.3 on 2023-09-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_alter_productitem_product_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon_code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=150)),
                ("discount", models.IntegerField()),
            ],
        ),
    ]
