# Generated by Django 4.2.3 on 2023-09-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_coupon_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon_code",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
