# Generated by Django 4.2.3 on 2023-10-05 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_product_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_review",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="products.productitem",
            ),
        ),
    ]
